project_id = "wiylggtouvdspdrymzlr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_email_confirmations = false
enable_email_change_confirmations = false
enable_phone_confirmations = false
enable_phone_change_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false

[db]
shadow_port = 54320
port = 54322

[functions.generate-article]
verify_jwt = true

[functions.auto-content-cron]
verify_jwt = false

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323

[storage]
enabled = true
port = 54324
image_transformation = {
  enabled = true
}

[edge-runtime]
enabled = true
port = 54325
ip_version = "ipv4"

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"