-- Primero eliminamos el constraint problemático
ALTER TABLE posts DROP CONSTRAINT IF EXISTS check_published_seo;

-- Insertamos los artículos de prueba
INSERT INTO posts (title, slug, excerpt, content, image_url, category, published, featured, reading_time, author_id, meta_title, meta_description) VALUES 
('Revolución de la IA en la Educación 2024', 'revolucion-ia-educacion-2024', 'Descubre cómo la inteligencia artificial está transformando las aulas y el aprendizaje personalizado.', '<h2>La nueva era educativa</h2><p>La inteligencia artificial está revolucionando la forma en que enseñamos y aprendemos. Desde plataformas adaptativas hasta tutores virtuales, exploramos las tendencias más importantes de 2024.</p><h3>Herramientas destacadas</h3><ul><li>Sistemas de tutoría personalizada</li><li>Análisis predictivo del rendimiento</li><li>Generación automática de contenido</li></ul>', 'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=800&h=600&fit=crop', 'educacion', true, true, 8, 'f3c0d68e-47ad-40d4-9bbd-4cb8c8018f7e', 'Revolución de la IA en la Educación 2024', 'Descubre cómo la inteligencia artificial está transformando las aulas y el aprendizaje personalizado en 2024.'),

('Las Mejores Apps Educativas del Año', 'mejores-apps-educativas-ano', 'Analizamos las aplicaciones más innovadoras que están cambiando la educación digital.', '<h2>Top de aplicaciones educativas</h2><p>Este año ha traído aplicaciones increíbles que están facilitando el aprendizaje en todas las edades. Desde matemáticas hasta idiomas, estas herramientas están marcando la diferencia.</p><h3>Categorías destacadas</h3><ul><li>Matemáticas interactivas</li><li>Aprendizaje de idiomas</li><li>Ciencias experimentales</li><li>Historia inmersiva</li></ul>', 'https://images.unsplash.com/photo-1512486130939-2c4f79935e4f?w=800&h=600&fit=crop', 'tecnologia', true, true, 6, 'f3c0d68e-47ad-40d4-9bbd-4cb8c8018f7e', 'Las Mejores Apps Educativas del Año', 'Analizamos las aplicaciones más innovadoras que están cambiando la educación digital.'),

('Tendencias en Educación Virtual', 'tendencias-educacion-virtual', 'El futuro del aprendizaje online: realidad aumentada, gamificación y más.', '<h2>El futuro es virtual</h2><p>La educación virtual ha evolucionado más allá de las videollamadas. Nuevas tecnologías como la realidad aumentada y la gamificación están creando experiencias de aprendizaje inmersivas.</p><h3>Tecnologías emergentes</h3><ul><li>Realidad virtual en el aula</li><li>Gamificación del aprendizaje</li><li>Microlearning</li><li>Blockchain para certificaciones</li></ul>', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=600&fit=crop', 'tendencias', true, true, 7, 'f3c0d68e-47ad-40d4-9bbd-4cb8c8018f7e', 'Tendencias en Educación Virtual', 'El futuro del aprendizaje online: realidad aumentada, gamificación y más.'),

('Innovación en Metodologías Pedagógicas', 'innovacion-metodologias-pedagogicas', 'Métodos revolucionarios que están transformando la enseñanza tradicional.', '<h2>Nuevos enfoques pedagógicos</h2><p>Los educadores están adoptando metodologías innovadoras que priorizan el aprendizaje activo y la participación estudiantil. Exploramos las técnicas más efectivas.</p>', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&h=600&fit=crop', 'innovacion', true, false, 5, 'f3c0d68e-47ad-40d4-9bbd-4cb8c8018f7e', 'Innovación en Metodologías Pedagógicas', 'Métodos revolucionarios que están transformando la enseñanza tradicional.'),

('Herramientas para Docentes Modernos', 'herramientas-docentes-modernos', 'Las mejores plataformas y recursos digitales para educadores del siglo XXI.', '<h2>Equipando a los educadores</h2><p>Los docentes de hoy necesitan herramientas digitales poderosas. Analizamos las plataformas más útiles para gestión de aulas, creación de contenido y evaluación.</p>', 'https://images.unsplash.com/photo-1581726690015-c9861fa5057f?w=800&h=600&fit=crop', 'tecnologia', true, false, 4, 'f3c0d68e-47ad-40d4-9bbd-4cb8c8018f7e', 'Herramientas para Docentes Modernos', 'Las mejores plataformas y recursos digitales para educadores del siglo XXI.'),

('El Futuro de la Evaluación Digital', 'futuro-evaluacion-digital', 'Sistemas inteligentes de evaluación que van más allá de los exámenes tradicionales.', '<h2>Evolución en la evaluación</h2><p>La evaluación educativa está experimentando una transformación digital. Nuevos sistemas permiten evaluaciones más precisas y personalizadas del progreso estudiantil.</p>', 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=600&fit=crop', 'innovacion', true, false, 6, 'f3c0d68e-47ad-40d4-9bbd-4cb8c8018f7e', 'El Futuro de la Evaluación Digital', 'Sistemas inteligentes de evaluación que van más allá de los exámenes tradicionales.');

-- Añadimos el campo is_hero_pinned para marcar artículos fijos del hero
ALTER TABLE posts ADD COLUMN is_hero_pinned BOOLEAN DEFAULT false;

-- Marcamos algunos artículos como fijos del hero
UPDATE posts SET is_hero_pinned = true WHERE slug IN ('revolucion-ia-educacion-2024', 'mejores-apps-educativas-ano', 'tendencias-educacion-virtual');